version: "3.9"
services:
  kwaba-api:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - kwaba_ignore:/app/node_modules/
    environment:
      - NODE_ENV=development
    command: npm run dev
volumes:
  kwaba_ignore: